#!/bin/bash
while :
do
  NOWS=`date +%S`
  NOWM=`date +%M | cut -c2`
  if [ $NOWS -eq 0 ]; then
    # execute capture if second is 0
    capture.php
    echo ""
  else
    echo -ne "Sleeping until top of next minute ... (now $NOWM : $NOWS) \r"
    # sleep quarter a second
    sleep 0.25
  fi
done
